//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chore
    {
        public int SrNo { get; set; }
        public Nullable<int> PriestID { get; set; }
        public Nullable<int> Resonsibilities { get; set; }
    
        public virtual Priest Priest { get; set; }
        public virtual Responsibility Responsibility { get; set; }
    }
}
