//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public int SrNo { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Daily { get; set; }
        public Nullable<decimal> Monthly { get; set; }
        public Nullable<decimal> Yearly { get; set; }
    }
}
