//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrasadamDistribution
    {
        public int SrNo { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> PriestID { get; set; }
        public Nullable<int> SweetDishIDs { get; set; }
        public Nullable<int> RiceItemIDs { get; set; }
        public int Quantity { get; set; }
    
        public virtual Priest Priest { get; set; }
        public virtual RiceItemsList RiceItemsList { get; set; }
        public virtual SweetDishesList SweetDishesList { get; set; }
    }
}
