//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Priest()
        {
            this.Chores = new HashSet<Chore>();
            this.PrasadamDistributions = new HashSet<PrasadamDistribution>();
        }
    
        public int PriestID { get; set; }
        public string Name { get; set; }
        public int ContactNumber { get; set; }
        public System.DateTime DOJ { get; set; }
        public string LockerNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chore> Chores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrasadamDistribution> PrasadamDistributions { get; set; }
    }
}
