//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Assessment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TempleDBEntities : DbContext
    {
        public TempleDBEntities()
            : base("name=TempleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expence> Expences { get; set; }
        public virtual DbSet<Priest> Priests { get; set; }
        public virtual DbSet<Responsibility> Responsibilities { get; set; }
        public virtual DbSet<RiceItemsList> RiceItemsLists { get; set; }
        public virtual DbSet<SweetDishesList> SweetDishesLists { get; set; }
        public virtual DbSet<Chore> Chores { get; set; }
        public virtual DbSet<PrasadamDistribution> PrasadamDistributions { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
